ci:
  autofix_prs: true
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml

- repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
  rev: v1.1.2
  hooks:
  - id: markdown-toc
    files: README.md

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.240
  hooks:
  - id: ruff
    args: [--fix]

- repo: https://github.com/MarcoGorelli/cython-lint
  rev: v0.12.0
  hooks:
  - id: cython-lint

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
